### ISSUE TITLE
import ppmilib

### ISSUE THREAD

**Issue by AlexLilloo** [sameerd/ppmi#1]
Hello, 

I am trying to use your database but i have a problem.
When i execute the next command:
· "python scripts/create_ppmi_database.py"
This error appears:

Traceback (most recent call last):
  File "scripts/create_ppmi_database.py", line 8, in <module>
    import ppmilib
ImportError: No module named ppmilib

I do not know how to install this lib. When i execute that:

·"sudo pip3 install ppmilib"

This error appears: 

Collecting ppmilib
  ERROR: Could not find a version that satisfies the requirement ppmilib (from versions: none)
ERROR: No matching distribution found for ppmilib

And i dont know where can i download the requirements.

Can you help me please?

Thank you very much.

Alejandro.

**Comment by sameerd** [comment]
Hi, I'm on vacation this week. Will write back to you early next week when
I get to a computer.

Rgds.

**Comment by sameerd** [comment]
Hi, I ran into this problem as well. It is because the python path doesn't include the current directory. Try creating the database this way and that imports the `ppmilib` module. 
```
cd scripts/python
PYTHONPATH=.:$PYTHONPATH scripts/create_ppmi_database.py
```
